---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure packages are updated
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      become: yes
      tags:
        - molecule-idempotence-notest

    - name: Ensure that unzip is installed
      ansible.builtin.apt:
        name: unzip
      become: yes

    - name: Check if we are running on Parrot GNU/Linux
      ansible.builtin.set_fact:
        running_on_parrot: "{{ True if ansible_facts['os_family'] == 'Parrot GNU/Linux' else False }}"

    - import_tasks: "{{ playbook_dir }}/tasks/parrot_os.yml"
      when: running_on_parrot

- ansible.builtin.import_playbook: "{{ playbook_dir }}/tasks/roles.yml"

- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    username: "{{ ansible_user_id }}"
  tasks:
    - ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/dotfiles.yml"
    - ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/apt_packages.yml"
    - ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/snap_packages.yml"
    - ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/vscode.yml"
