---
- name: Check if ulauncher is installed
  ansible.builtin.command: dpkg-query -W ulauncher
  register: ulauncher_check_deb
  failed_when: ulauncher_check_deb.rc > 1
  changed_when: ulauncher_check_deb.rc == 1

- name: Download ulauncher
  ansible.builtin.get_url:
    url: https://github.com/ulauncher/ulauncher/releases/download/5.8.0/ulauncher_5.8.0_all.deb
    dest: "/tmp/ulauncher_5.8.0_all.deb"
    checksum: sha256:29c6e673c44340d08fd7617d1030c8ef6719926b1ebd8d8db1c680d80e566778
  when: ulauncher_check_deb.rc == 1

- name: Install ulauncher
  ansible.builtin.apt:
    deb: "/tmp/ulauncher_5.8.0_all.deb"
  become: yes
  when: ulauncher_check_deb.rc == 1

- name: Install ulauncher
  ansible.builtin.apt:
    deb: "/tmp/ulauncher_5.8.0_all.deb"
  become: yes
  when: ulauncher_check_deb.rc == 1

- name: Check if Hyper is installed
  ansible.builtin.command: dpkg-query -W hyper
  register: hyper_check_deb
  failed_when: hyper_check_deb.rc > 1
  changed_when: hyper_check_deb.rc == 1

- name: Download Hyper
  ansible.builtin.get_url:
    url: https://github.com/vercel/hyper/releases/download/v3.1.2/hyper_3.1.2_amd64.deb
    dest: "/tmp/hyper_3.1.0-canary.4_amd64.deb"
    checksum: sha256:af7872e791d2a0c13b67ea864e1370b32181f0f14db5f81ab76bb54761f23dd6
  when: hyper_check_deb.rc == 1

- name: Install Hyper dependencies
  ansible.builtin.apt:
    name:
      - libappindicator1
  become: yes
  when: hyper_check_deb.rc == 1

- name: Install Hyper
  ansible.builtin.apt:
    deb: "/tmp/hyper_3.1.2_amd64.deb"
  become: yes
  when: hyper_check_deb.rc == 1

- name: Setup SUID for /opt/Hyper/chrome-sandbox
  ansible.builtin.file:
    path: /opt/Hyper/chrome-sandbox
    owner: root
    group: root
    mode: '4755'
  become: yes

- name: Check if bat is installed
  ansible.builtin.command: dpkg-query -W bat
  register: bat_check_deb
  failed_when: bat_check_deb.rc > 1
  changed_when: bat_check_deb.rc == 1

- name: Download bat
  ansible.builtin.get_url:
    url: https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb
    dest: "/tmp/bat_0.15.4_amd64.deb"
    checksum: sha256:66b5fa31e4946da9331824fba4b6a7076565fe83866f14562450a010a5112857
  when: bat_check_deb.rc == 1

- name: Install bat
  ansible.builtin.apt:
    deb: "/tmp/bat_0.15.4_amd64.deb"
  become: yes
  when: bat_check_deb.rc == 1

- name: Check if ripgrep is installed
  ansible.builtin.command: dpkg-query -W ripgrep
  register: ripgrep_check_deb
  failed_when: ripgrep_check_deb.rc > 1
  changed_when: ripgrep_check_deb.rc == 1

- name: Download ripgrep
  ansible.builtin.get_url:
    url: https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
    dest: "/tmp/ripgrep_11.0.2_amd64.deb"
    checksum: sha256:cecbe73abf3c672fde070c5c1d2ea303d97dae0af9afa0655028ae0d70dd11e8
  when: ripgrep_check_deb.rc == 1

- name: Install ripgrep
  ansible.builtin.apt:
    deb: "/tmp/ripgrep_11.0.2_amd64.deb"
  become: yes
  when: ripgrep_check_deb.rc == 1

- name: Install packages using the systems package manager 1/2
  ansible.builtin.apt:
    name:
      - stow
      - ncdu
      - tmux
      - ranger
      - snapd
      - keepass2
      - adb
      - flameshot
      - jq
      - strace
      - ltrace
      - fonts-noto-color-emoji
    state: latest
  become: yes

- name: Install packages using the systems package manager 2/2
  ansible.builtin.apt:
    name:
      - virtualbox
    state: latest
  become: yes
  tags:
    - molecule-notest
