---
- name: Install packages using the systems package manager
  ansible.builtin.apt:
    name:
      - stow
      - ncdu
      - tmux
      - ranger
      - snapd
      - keepass2
      - adb
      # - flameshot
      - jq
      - strace
      - ltrace
      - fonts-noto-color-emoji
    state: latest
  become: yes
