---
- name: install vscode extension.
  ansible.builtin.command: "code --install-extension {{ item }}"
  become: no
  register: result
  with_items:
    - shan.code-settings-sync
  changed_when:
    - result.stdout is not search('is already installed.')
  tags:
    - molecule-notest
